/*
   Copyright(c) 2020 Alain Royer.
   Email: aroyer.qc@gmail.com

   Permission is hereby granted, free of charge, to any person obtaining a copy of this software
   and associated documentation files (the "Software"), to deal in the Software without
   restriction, including without limitation the rights to use, copy, modify, merge, publish,
   distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the
   Software is furnished to do so, subject to the following conditions:

   The above copyright notice and this permission notice shall be included in all copies or
   substantial portions of the Software.

   THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
   INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
   AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
   DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
   OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

#include "mainwindow.h"
#include "ui_mainwindow.h"
#include "Utility.h"
#include "compression.h"
#include <QRegExp>


// ************************************************************************************************
// *
// *  Slot
// *
// ************************************************************************************************

void MainWindow::on_ButtonBrowse_clicked()
{
    QString SelectedDir = getDirectoryFromDialog(this, tr("Find Images Files"), m_CurrentDir.absolutePath());

    if (!SelectedDir.isEmpty())
    {
        if(ui->ComboBoxDirectory->findText(SelectedDir) == -1)
        {
            ui->ComboBoxDirectory->addItem(SelectedDir);
        }
        ui->ComboBoxDirectory->setCurrentIndex(ui->ComboBoxDirectory->findText(SelectedDir));
    }
}

// ************************************************************************************************

void MainWindow::on_ComboBoxDirectory_currentIndexChanged(int index)
{
    Q_UNUSED(index);
    m_CurrentDir = QDir(ui->ComboBoxDirectory->currentText());
    SetConfigToXML();
    Find();
}

// ************************************************************************************************

void MainWindow::on_comboBoxPixelFormat_currentIndexChanged(int index)
{
    if(index == FORMAT_RGB565)        m_PixelFormatConverter = QImage::Format_RGB16;
    else if(index == FORMAT_ARGB8888) m_PixelFormatConverter = QImage::Format_ARGB32;

    if(index == FORMAT_FILE_DATA)
    {
       m_PixelFormatConverter = QImage::Format_Invalid;
       ui->comboBoxResize->setCurrentIndex(0);
       ui->comboBoxResize->setEnabled(false);
    }
    else
    {
       ui->comboBoxResize->setEnabled(true);
       ReloadImageConverter();
    }

}

// ************************************************************************************************

void MainWindow::on_comboBoxResize_currentIndexChanged(int index)
{
    Q_UNUSED(index);

    if(m_PixelFormatConverter != QImage::Format_Invalid)
    {
        ReloadImageConverter();
    }
}

// ************************************************************************************************

void MainWindow::on_ButtonConvert_clicked()
{
    on_TableFilesFound_cellActivated(ui->TableFilesFound->currentRow(), 0);
}


void MainWindow::on_ButtonLoadBackGround_clicked()
{
   LoadBackgroundImage();
}

// ************************************************************************************************

void MainWindow::on_TableFilesFound_cellActivated(int row, int column)
{
    QTableWidgetItem* item = ui->TableFilesFound->item(row, 0);
    QString FileName = m_CurrentDir.absoluteFilePath(item->text());
    QFileInfo FileInfo(FileName);
    QString BaseName = FileInfo.baseName();                     // Get the file name without extension
    QString Temp;
    QString Format;
    int IndexFormat;
    QVector<uint8_t> Data;
    int Count;
    int CompressionIndex;

    Q_UNUSED(column);

    // Replace '-' or ' ' by '_' with regex
    QRegExp Regex("[- ]+");
    int s = -1;
    while((s = Regex.indexIn(BaseName, s + 1)) >= 0)
    {
        BaseName[s] = '_';
    }

    // Replace all numeric from the beginning of the name
    Regex.setPattern("[^0-9]+[_A-Za-z0-9]+");
    if(Regex.indexIn(BaseName, 0) >= 0)
    {
        BaseName = Regex.cap(0);
    }

    // Stream data to file
    QFile File(BaseName + ".cpp");
    if(File.open(QIODevice::WriteOnly))
    {
        QTextStream Stream(&File);

        Stream << "//-------------------------------------------\r\n";
        Stream << "// This file was autogenerated by GUI Builder\r\n";
        Stream << "//-------------------------------------------\r\n\r\n";
        Stream << "#include \"./lib_digini.h\"\r\n\r\n";
        Stream << "#ifdef DIGINI_USE_GRAFX\r\n\r\n";
        Stream << "//-------------------------------------------\r\n\r\n";

        IndexFormat = ui->comboBoxPixelFormat->currentIndex();

        if((IndexFormat == FORMAT_RGB565) || (IndexFormat == FORMAT_ARGB8888))
        {
            this->Extract(&Data, IndexFormat, &CompressionIndex);
            Count = PrintArrayBody(Stream, Data, BaseName, IndexFormat, CompressionIndex);
        }

        Stream << "const StaticImageInfo_t SII_" << BaseName << " =\r\n";
        Stream << "{\r\n    {\r\n        (void*)";
        Stream << BaseName << ",\r\n";
        Temp = QString("%1").arg(m_Scale.width());
        Stream << "        {" << Temp.toUtf8() << ", ";
        Temp = QString("%1").arg(m_Scale.height());
        Stream << Temp.toUtf8() << "},\r\n        PIXEL_FORMAT_";

        switch(IndexFormat)
        {
        case FORMAT_RGB565:   { Format = QString("RGB565");   break;}
        case FORMAT_ARGB8888: { Format = QString("ARGB8888"); break;}
        }

        Stream << Format;
        Stream << "\r\n    },\r\n";
        Temp = QString("%1").arg(Count);
        Stream << "    " << Temp.toUtf8() << ",\r\n    COMPX_";

        switch(CompressionIndex)
        {
            case COMPRESSION_NONE:   Stream << "COMPRESSION_NONE";      break;
            case RLE_16:             Stream << "RLE_16";                break;
            case RLE_32:             Stream << "RLE_32";                break;
        }

        Stream << "\r\n};\r\n\r\n";
        Stream << "//-------------------------------------------------------------------------------------------------\r\n\r\n";
        Stream << "#endif // DIGINI_USE_GRAFX\r\n";


        File.close();
    }
}

// ************************************************************************************************

int MainWindow::PrintArrayBody(QTextStream& Stream, const QVector<uint8_t>& Data, QString& BaseName, int IndexFormat, int& CompressionIndex)
{
    int ElementSize = (IndexFormat == FORMAT_RGB565) ? sizeof(uint16_t) : sizeof(uint32_t);
    int Count;
    bool IsItStruct = false;

    if(ElementSize == sizeof(uint16_t))
    {
        if(CompressionIndex == RLE_16)
        {
            Stream << "const StaticImageRLE_16_t " << BaseName;
            Count = Data.size() / (ElementSize + sizeof(uint8_t));
            IsItStruct = true;
        }
        else
        {
            Stream << "const uint16_t " << BaseName;
            Count = Data.size() / ElementSize;
        }
    }
    else // (ElementSize == sizeof(uint32_t))
    {
        if(CompressionIndex == RLE_32)
        {
            Stream << "const StaticImageRLE_32_t " << BaseName;
            Count = Data.size() / (ElementSize + sizeof(uint8_t));
            IsItStruct = true;
        }
        else
        {
            Stream << "const uint32_t " << BaseName;
            Count = Data.size() / ElementSize;
        }
    }

    Stream << "[" << Count << "] =\r\n{\r\n    ";

    int PerLine = 0;

    if(IsItStruct == false)
    {
        for(int i = 0; i < Count; i++)
        {
            QString Temp;

            if(ElementSize == 2)
            {
                uint16_t v = ((uint16_t)Data[2*i] << 8) | ((uint16_t)Data[2*i+1]);
                Temp = QString("%1").arg(v, 4, 16, QChar('0')).toUpper();
            }
            else
            {
                uint32_t v = ((uint32_t)Data[4*i]     << 24) |
                             ((uint32_t)Data[4*i + 1] << 16) |
                             ((uint32_t)Data[4*i + 2] << 8)  |
                             ((uint32_t)Data[4*i + 3]);
                Temp = QString("%1").arg(v, 8, 16, QChar('0')).toUpper();
            }

            Stream << "0x" << Temp;

            if(i + 1 < Count)
                Stream << ", ";

            PerLine++;

            if(PerLine == 16)
            {
                PerLine = 0;
                Stream << "\r\n    ";
            }
        }
    }
    else
    {
        int i = 0;

        while(i < Data.size())
        {
            // Read repeat (1 byte)
            uint8_t Repeat = Data[i];
            i += 1;

            // Read pixel (2 or 4 bytes)
            uint32_t pixel = 0;

            if(ElementSize == 2)   // RLE16
            {
                pixel = ((uint16_t)Data[i]   << 8) |
                        ((uint16_t)Data[i+1]);
                i += 2;
            }
            else                   // RLE32
            {
                pixel = ((uint32_t)Data[i]   << 24) |
                        ((uint32_t)Data[i+1] << 16) |
                        ((uint32_t)Data[i+2] << 8)  |
                        ((uint32_t)Data[i+3]);
                i += 4;
            }

            // Print struct
            Stream << "{ 0x"
                   << QString("%1").arg(Repeat, 2, 16, QChar('0')).toUpper()
                   << ", 0x"
                   << QString("%1").arg(pixel,
                                        (ElementSize == 2 ? 4 : 8),
                                        16,
                                        QChar('0')).toUpper()
                   << " }";

            PerLine++;

            // Add comma at end of line (except last element)
            if(i < Data.size())
                Stream << ", ";

            // Line break every 8 structs
            if(PerLine == 8 && i < Data.size())
            {
                Stream << "\r\n    ";
                PerLine = 0;
            }
        }
    }

    Stream << "\r\n};\r\n\r\n";

    return Count;
}

// ************************************************************************************************

void MainWindow::on_TableFilesFound_currentCellChanged(int currentRow, int currentColumn, int previousRow, int previousColumn)
{
    Q_UNUSED(currentColumn);
    Q_UNUSED(previousRow);
    Q_UNUSED(previousColumn);
    if(currentRow >= 0)
    {
        ui->comboBoxResize->setEnabled(true);
        LoadImageConverter(currentRow, AUTO_FORMAT);
    }
}

// ************************************************************************************************

void MainWindow::on_TableFilesFound_cellClicked(int row, int column)
{
    Q_UNUSED(column);
    LoadImageConverter(row, AUTO_FORMAT);
}

// ************************************************************************************************

void MainWindow::on_horizontalScrollBarConverter_valueChanged(int value)
{
    int PosX = value / 100;
    int PosY = m_pPixmapItem->y();
    m_pPixmapItem->setPos(-PosX, PosY);
}

// ************************************************************************************************

void MainWindow::on_verticalScrollBarConverter_valueChanged(int value)
{
    int PosX = m_pPixmapItem->x();
    int PosY = value / 100;
    m_pPixmapItem->setPos(PosX, -PosY);
}

// ************************************************************************************************

void MainWindow::on_CheckerBoardSlider_sliderMoved(int position)
{
   ui->graphicsViewConverter->setStyleSheet(QString("background-color: #%1;").arg(position + (position << 8) + (position << 16), 6, 16, QChar('0')));
   CheckerPattern(&m_SceneConverter);
}

// ************************************************************************************************
// *
// *  Function
// *
// ************************************************************************************************

void MainWindow::InitConverter()
{
    m_pImage          = nullptr;
    m_pProcessedImage = nullptr;
    m_pBackgroundImage = nullptr;
    m_pBackgroundItem = nullptr;

    ui->ComboBoxDirectory->blockSignals(true);
    ui->ComboBoxDirectory->setCurrentText(m_CurrentDir.absolutePath());
    UpdateComboBox(ui->ComboBoxDirectory);
    ui->ComboBoxDirectory->blockSignals(false);

    on_CheckerBoardSlider_sliderMoved(DEFAULT_CHECKER_VALUE);
    ui->CheckerBoardSlider->setSliderPosition(DEFAULT_CHECKER_VALUE);

    Find();
}

// ************************************************************************************************

void MainWindow::ResetConverterGUI()
{
    ui->horizontalScrollBarConverter->setRange     (0, 0);
    ui->verticalScrollBarConverter->setRange       (0, 0);
    ui->horizontalScrollBarConverter->setSingleStep(0);
    ui->verticalScrollBarConverter->setSingleStep  (0);
    ui->comboBoxResize->setCurrentIndex(SCALE_FIT);
    ui->LabelNoteConverter->setVisible(false);
    ui->ButtonConvert->setDisabled(true);
    ui->LabelFilename->setText("");
    ui->LabelPixelFormat->setText("");
    ui->LabelSize->setText("");
    ClearTable(ui->TableFilesFound);
    ClearSceneConverter();
}

// ************************************************************************************************

void MainWindow::ClearSceneConverter()
{
    m_SceneConverter.clear();
    ui->graphicsViewConverter->setSceneRect(0, 0, m_SkinConfig.DisplaySize.width(), m_SkinConfig.DisplaySize.height());
    CheckerPattern(&m_SceneConverter);
    ui->graphicsViewConverter->setScene(&m_SceneConverter);
    int position = ui->CheckerBoardSlider->value();  // Update checker board to default value of ui slider
    ui->graphicsViewConverter->setStyleSheet(QString("background-color: #%1;").arg(position + (position << 8) + (position << 16), 6, 16, QChar('0')));
}

// ************************************************************************************************

void MainWindow::LoadBackgroundImage()
{
    QString Filename = QFileDialog::getOpenFileName(
        this,
        "Select Background Image",
        m_CurrentDir.absolutePath(),
        "Images (*.png *.jpg *.bmp)"
        );

    if(Filename.isEmpty())
        return;

    if(m_pBackgroundImage != nullptr)
    {
        delete m_pBackgroundImage;
        m_pBackgroundImage = nullptr;
    }

    m_pBackgroundImage = new QImage();
    m_pBackgroundImage->load(Filename);

    // Redraw scene
    ReloadSceneWithBackground();
}

// ************************************************************************************************

void MainWindow::ApplyConverterDisplaySize()
{
    QSize sz = m_SkinConfig.DisplaySize;

    // Resize the graphics view of the converter
    ui->graphicsViewConverter->setMinimumSize(sz);
    ui->graphicsViewConverter->resize(sz);

    // Resize the scene
    ui->graphicsViewConverter->setSceneRect(0, 0, sz.width(), sz.height());

    // Optionnel : ajuster la fenêtre
    this->adjustSize();
}

// ************************************************************************************************

void MainWindow::ReloadSceneWithBackground()
{
    ClearSceneConverter();   // Remet le checkerboard

    if(m_pBackgroundImage != nullptr)
    {
        QPixmap Pix = QPixmap::fromImage(*m_pBackgroundImage);
        m_pBackgroundItem = m_SceneConverter.addPixmap(Pix);
        m_pBackgroundItem->setZValue(-10);   // Sous tout
        m_pBackgroundItem->setPos(0, 0);
    }

    // Si une image convertie existe, on la remet par-dessus
    if(m_pProcessedImage != nullptr)
    {
        m_pPixmapItem = m_SceneConverter.addPixmap(QPixmap::fromImage(*m_pProcessedImage));
        QPoint Point = CenterPoint(m_pProcessedImage->size(), m_SkinConfig.DisplaySize);
        m_pPixmapItem->setPos(Point);
        m_pPixmapItem->setZValue(10);
    }

    ui->graphicsViewConverter->setScene(&m_SceneConverter);
}

// ************************************************************************************************

void MainWindow::Find()
{
    QStringList files;
    QStringList filters;

    ResetConverterGUI();

    filters << "*.png" << "*.bmp" << "*.jpg";
    m_CurrentDir.setNameFilters(filters);

    files = m_CurrentDir.entryList(filters, QDir::Files | QDir::NoSymLinks);

    m_FileFound = files.size();
    m_SceneConverter.clear();

    ui->TableFilesFound->blockSignals(true);
    for(int i = 0; i < m_FileFound; ++i)
    {
        QFile file(m_CurrentDir.absoluteFilePath(files[i]));
        qint64 size = QFileInfo(file).size();

        QTableWidgetItem *fileNameItem = new QTableWidgetItem(files[i]);
        fileNameItem->setFlags(fileNameItem->flags() ^ Qt::ItemIsEditable);
        QTableWidgetItem *sizeItem = new QTableWidgetItem(PrintFileSize(size));
        sizeItem->setTextAlignment(Qt::AlignRight | Qt::AlignVCenter);
        sizeItem->setFlags(sizeItem->flags() ^ Qt::ItemIsEditable);

        ui->TableFilesFound->insertRow(i);
        ui->TableFilesFound->setItem(i, 0, fileNameItem);
        ui->TableFilesFound->setItem(i, 1, sizeItem);
    }
    ui->TableFilesFound->blockSignals(false);

    if(m_FileFound)
    {
        ui->LabelFilesFoundConverter->setText(tr("%1 file(s) found").arg(m_FileFound));
    }
    else
    {
        ui->LabelFilesFoundConverter->setText(tr("0 file found"));
    }
}

// ************************************************************************************************

void MainWindow::ReloadImageConverter()
{
    int row = ui->TableFilesFound->currentRow();
    if(row >= 0)
    {
        LoadImageConverter(row, RELOAD_FORMAT);
    }
}

// ************************************************************************************************

void MainWindow::LoadImageConverter(int row, Resizer_e Resizer)
{
    QTableWidgetItem *item;
    QString Filename;
    QString PathAndFilename;

    ui->ButtonConvert->setEnabled(true);
    item = ui->TableFilesFound->item(row, 0);
    Filename        = item->text();
    PathAndFilename = m_CurrentDir.absoluteFilePath(Filename);
    m_FileSize      = QFileInfo(PathAndFilename).size();

    if(m_pImage != nullptr)
    {
        delete m_pImage;
        m_pImage = nullptr;
    }

    m_pImage = new QImage();
    m_pImage->load(PathAndFilename);

    //m_pImage = new QImage(m_pImage->convertToFormat(QImage::Format_ARGB32));
    // Information that do not change if setting change
    ui->LabelFilename->setText(item->text());
    ui->LabelFilename->setStyleSheet(QString("color: black;"));
    ui->LabelSize->setText(PrintSize(m_pImage->size()));
    ui->LabelSize->setStyleSheet(QString("color: black;"));

    if(Resizer == AUTO_FORMAT)
    {
        m_PixelFormatConverter = AutoSelectConversion(ui->comboBoxPixelFormat, m_pImage->format());
    }

    // Redraw Image
    QPoint  Point;
    QSize   Size;
    QImage* pResizedImage;

    ClearSceneConverter();

    if(m_pBackgroundImage != nullptr)
    {
        QGraphicsPixmapItem* pBg = m_SceneConverter.addPixmap(QPixmap::fromImage(*m_pBackgroundImage));
        pBg->setZValue(-10);   // Sous tout
        pBg->setPos(0, 0);
    }

    pResizedImage = new QImage();
    ScaleToRequirement(m_pImage, pResizedImage, &m_SkinConfig.DisplaySize, (Scale_e)ui->comboBoxResize->currentIndex());

    if(m_pProcessedImage != nullptr)
    {
        delete m_pProcessedImage;
        m_pProcessedImage = nullptr;
    }

    m_pProcessedImage = new QImage();
    *m_pProcessedImage = pResizedImage->convertToFormat(m_PixelFormatConverter);
    delete pResizedImage;

    // Set the size for the image info
    m_Scale.setWidth((m_pProcessedImage->width()   > m_SkinConfig.DisplaySize.width())  ? m_SkinConfig.DisplaySize.width()  : m_pProcessedImage->width());
    m_Scale.setHeight((m_pProcessedImage->height() > m_SkinConfig.DisplaySize.height()) ? m_SkinConfig.DisplaySize.height() : m_pProcessedImage->height());

    m_TotalCount  = m_pProcessedImage->sizeInBytes() / (m_pProcessedImage->width() * m_pProcessedImage->height());    // Adjust byte count to image size in viewport if it is the case
    m_TotalCount *= (m_Scale.width() * m_Scale.height());

    // Update Static Label
    ui->LabelStaticFileInfo->setStyleSheet(QString("color: black;"));
    ui->LabelStaticFilename->setStyleSheet(QString("color: black;"));
    ui->LabelStaticFileDataSize->setStyleSheet(QString("color: black;"));
    ui->LabelStaticDataSize->setStyleSheet(QString("color: black;"));
    ui->LabelStaticPixelFormat->setStyleSheet(QString("color: black;"));
    ui->LabelStaticSize->setStyleSheet(QString("color: black;"));
    ui->LabelStaticScaleSize->setStyleSheet(QString("color: black;"));
    ui->LabelStaticCheckerColor->setStyleSheet(QString("color: black;"));
    ui->LabelStaticConvertTo->setStyleSheet(QString("color: black;"));
    ui->LabelStaticResize->setStyleSheet(QString("color: black;"));
    ui->LabelStaticCompress->setStyleSheet(QString("color: black;"));

    ui->LabelPixelFormat->setText(GetFormat(m_pImage->format()));
    ui->LabelPixelFormat->setStyleSheet(QString("color: black;"));

    ui->LabelDataSize->setText(QString("%1 Bytes").arg(m_TotalCount));                                              // Print updated value in information
    ui->LabelDataSize->setStyleSheet(QString("color: black;"));

    ui->LabelFileDataSize->setText(QString("%1 Bytes").arg(m_FileSize));
    ui->LabelFileDataSize->setStyleSheet(QString("color: black;"));

    ui->LabelScaleSize->setText(PrintSize(m_Scale));                                                                // Display viewport size
    ui->LabelScaleSize->setStyleSheet(QString("color: black;"));

    // Set the size for the scene (minimum size is viewport)
    Size.setWidth ((m_pProcessedImage->width()  < m_SkinConfig.DisplaySize.width())  ? m_SkinConfig.DisplaySize.width()  : m_pProcessedImage->width());
    Size.setHeight((m_pProcessedImage->height() < m_SkinConfig.DisplaySize.height()) ? m_SkinConfig.DisplaySize.height() : m_pProcessedImage->height());

    if((Size.width()  > m_SkinConfig.DisplaySize.width()) ||                                                                   // Display special note if image is bigger than viewport
       (Size.height() > m_SkinConfig.DisplaySize.height()))
    {
        ui->LabelNoteConverter->setVisible(true);
    }
    else
    {
        ui->LabelNoteConverter->setVisible(false);
    }

    ui->horizontalScrollBarConverter->blockSignals(true);
    ui->verticalScrollBarConverter->blockSignals(true);
    ui->horizontalScrollBarConverter->setValue(0);
    ui->verticalScrollBarConverter->setValue(0);
    m_horizontalScrollRange = (m_pProcessedImage->size().width()  - m_SkinConfig.DisplaySize.width())  * 100;
    m_verticalScrollRange   = (m_pProcessedImage->size().height() - m_SkinConfig.DisplaySize.height()) * 100;
    ui->horizontalScrollBarConverter->setRange(0, m_horizontalScrollRange);
    ui->verticalScrollBarConverter->setRange  (0, m_verticalScrollRange);
    ui->horizontalScrollBarConverter->setSingleStep(m_horizontalScrollRange / 10);
    ui->verticalScrollBarConverter->setSingleStep  (m_verticalScrollRange / 10);
    ui->horizontalScrollBarConverter->blockSignals(false);
    ui->verticalScrollBarConverter->blockSignals(false);

    // Added image to the scene
    m_pPixmapItem = m_SceneConverter.addPixmap(QPixmap::fromImage(*m_pProcessedImage));                            // Add the image on top of the checker pattern
    Point = CenterPoint(m_pProcessedImage->size(), m_SkinConfig.DisplaySize);
    m_pPixmapItem->setPos(Point);
}

// ************************************************************************************************

int MainWindow::Extract(QVector<uint8_t>* pOutData, int Index, int* pCompressionIndex)
{
    QRgb Pixel;
    int X1, Y1, X2, Y2;

    QVector<uint8_t> RawData;
    pOutData->clear();

    // 1. Determine extraction region
    X1 = (ui->horizontalScrollBarConverter->value() / 100);
    Y1 = (ui->verticalScrollBarConverter->value() / 100);
    X2 = m_Scale.width()  + X1;
    Y2 = m_Scale.height() + Y1;

    // 2. Build RAW byte buffer
    for(int y = Y1; y < Y2; y++)
    {
        for(int x = X1; x < X2; x++)
        {
            Pixel = m_pProcessedImage->pixel(x, y);

            if(Index == FORMAT_RGB565)
            {
                uint16_t Value;
                Value  = (uint16_t)((Pixel >> 3) & 0x3F);
                Value |= (uint16_t)(((Pixel >> 19) & 0x1F) << 11);
                Value |= (uint16_t)(((Pixel >> 10) & 0x3F) << 5);

                RawData.append((uint8_t)(Value >> 8));
                RawData.append((uint8_t)(Value & 0xFF));
            }
            else if(Index == FORMAT_ARGB8888)
            {
                RawData.append((uint8_t)((Pixel >> 24) & 0xFF));
                RawData.append((uint8_t)((Pixel >> 16) & 0xFF));
                RawData.append((uint8_t)((Pixel >> 8)  & 0xFF));
                RawData.append((uint8_t)( Pixel        & 0xFF));
            }
        }
    }

    // 3. Select compression mode
    int MethodType = METHOD_TYPE_ALL;
    switch(ui->ComboCompress->currentIndex())
    {
        case 0: MethodType = METHOD_TYPE_NONE; break;
        
        case 1:
        {
            if      (Index == FORMAT_RGB565)   MethodType = METHOD_TYPE_RLE16;
            else if (Index == FORMAT_ARGB8888) MethodType = METHOD_TYPE_RLE32;
        }
        break;
        
        case 2: MethodType = METHOD_TYPE_LZW;  break;
    }

    // Compress
    *pCompressionIndex = Compress(pOutData, &RawData, RawData.size(), 0, MethodType);

    return pOutData->size();   // return compressed byte count
}


// ************************************************************************************************

void MainWindow::BinToFile(QTextStream* pStream, QString FileName)
{
    qint64 i;
    qint64 Size;
    qint64 TotalCounter;
    qint64 Counter;
    quint8 Byte;
    QString Temp;

    TotalCounter = 0;
    Counter = 0;

    // Stream data to file
    QFile File(FileName);
    
    if(File.open(QIODevice::ReadOnly))
    {
        Size = File.size();
        *pStream << "{\r\n    ";

        for(i = 0; i < Size; i++)
        {
            TotalCounter++;
            File.getChar((char*)&Byte);
            Temp = QString("%1").arg(Byte, 2, 16, QChar('0')).toUpper();
            *pStream << "0x" << Temp;

            if(TotalCounter != Size)
            {
               *pStream << ",";
                Counter++;

                if(Counter == 16)
                {
                    Counter = 0;
                    *pStream << "\r\n    ";
                }
            }
        }
        File.close();
   }

    *pStream << "\r\n};\r\n\r\n\r\n";
}

// ************************************************************************************************

void MainWindow::AdjustTabConverter(QSize Offset, QRect ViewRect)
{
    // Resize Vertical line
    setWidgetSize(ui->line_V_Converter,             -1,                                     Offset.height() + 226);

    // Resize Horizontal Line
    setWidgetSize(ui->line_H_Converter,             Offset.width() + 20,                    -1);

    // Reposition Horizontal Line
    setWidgetXY(ui->line_H_Converter,               -1,                                     Offset.height() + 25);
    setWidgetXY(ui->line_H_Converter_2,             -1,                                     Offset.height() + 235);

    // Reposition Label
    setWidgetXY(ui->LabelStaticFileInfo,            -1,                                     Offset.height() + 35);
    setWidgetXY(ui->LabelStaticFilename,            -1,                                     Offset.height() + 65);
    setWidgetXY(ui->LabelFilename,                  -1,                                     Offset.height() + 65);
    setWidgetXY(ui->LabelStaticFileDataSize,        -1,                                     Offset.height() + 95);
    setWidgetXY(ui->LabelFileDataSize,              -1,                                     Offset.height() + 95);
    setWidgetXY(ui->LabelStaticDataSize,            -1,                                     Offset.height() + 125);
    setWidgetXY(ui->LabelDataSize,                  -1,                                     Offset.height() + 125);
    setWidgetXY(ui->LabelStaticResize,              Offset.width() + 472,                   Offset.height() + 125);
    setWidgetXY(ui->LabelStaticPixelFormat,         -1,                                     Offset.height() + 155);
    setWidgetXY(ui->LabelPixelFormat,               -1,                                     Offset.height() + 155);
    setWidgetXY(ui->LabelStaticSize,                -1,                                     Offset.height() + 185);
    setWidgetXY(ui->LabelSize,                      -1,                                     Offset.height() + 185);
    setWidgetXY(ui->LabelStaticScaleSize,           -1,                                     Offset.height() + 215);
    setWidgetXY(ui->LabelScaleSize,                 -1,                                     Offset.height() + 215);
    setWidgetXY(ui->LabelFilesFoundConverter,       -1,                                     Offset.height() + 202);
    setWidgetXY(ui->LabelNoteConverter,             Offset.width() + 450,                   Offset.height() + 35);

    // Reposition Button
    setWidgetXY(ui->ButtonConvert,                  -1,                                     Offset.height() + 200);
    setWidgetXY(ui->ButtonLoadBackGround,           -1,                                     Offset.height() + 200);

    // Reposition Checker color slider
    setWidgetXY(ui->LabelStaticCheckerColor,        Offset.width() + 480,                   Offset.height() + 95);
    setWidgetXY(ui->CheckerBoardSlider,             Offset.width() + 580,                   Offset.height() + 99);

    // Reposition ComboBox and static label
    setWidgetXY(ui->LabelStaticConvertTo,           Offset.width() + 480,                   Offset.height() + 127);
    setWidgetXY(ui->comboBoxPixelFormat,            Offset.width() + 580,                   Offset.height() + 125);
    setWidgetXY(ui->LabelStaticResize,              Offset.width() + 480,                   Offset.height() + 167);
    setWidgetXY(ui->comboBoxResize,                 Offset.width() + 580,                   Offset.height() + 165);
    setWidgetXY(ui->LabelStaticCompress,            Offset.width() + 480,                   Offset.height() + 207);
    setWidgetXY(ui->ComboCompress,                  Offset.width() + 580,                   Offset.height() + 205);

    // Resize Table
    setWidgetSize(ui->TableFilesFound,              -1,                                     Offset.height() + 125);

    // Resize ScrollBar
    setWidgetSize(ui->horizontalScrollBarConverter, ViewRect.width(),                       -1);
    setWidgetSize(ui->verticalScrollBarConverter,   -1,                                     ViewRect.height());

    // Reposition VerticalScrollBar
    setWidgetXY(ui->horizontalScrollBarConverter,   ViewRect.x(),                           ViewRect.y() + ViewRect.height() + 5);
    setWidgetXY(ui->verticalScrollBarConverter,     ViewRect.x() + ViewRect.width() + 5,    ViewRect.y());

    // Reset ScrollBar cursor
    ClearScrollBarValue();

    //Resize GraphicsView
    ui->graphicsViewConverter->setGeometry(ViewRect);
    ui->graphicsViewConverter->setStyleSheet(QString("background-color: #%1;").arg(0, 6, 16, QChar('0')));
    ui->graphicsViewImage->setSceneRect(0, 0, ViewRect.width(), ViewRect.height());
    ui->graphicsViewImage->setStyleSheet(QString("background-color: #%1;").arg(0, 6, 16, QChar('0')));

    Find();
}

// ************************************************************************************************

void MainWindow::ClearScrollBarValue()
{
    ui->horizontalScrollBarConverter->blockSignals(true);
    ui->horizontalScrollBarConverter->setValue(0);
    ui->horizontalScrollBarConverter->blockSignals(false);
    ui->verticalScrollBarConverter->blockSignals(true);
    ui->verticalScrollBarConverter->setValue(0);
    ui->verticalScrollBarConverter->blockSignals(false);
}
